import os
import json
import logging
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI

load_dotenv()
logger = logging.getLogger("llm_client")

class LLMClient:
    """
    Wrapper using LangChain Google Generative AI (Gemini).
    Falls back to stub JSON if no GOOGLE_API_KEY is found.
    """

    def __init__(self):
        self.api_key = os.getenv("GOOGLE_API_KEY")
        self.model = os.getenv("LLM_MODEL", "gemini-2.5-flash")

        if self.api_key:
            try:
                self.client = ChatGoogleGenerativeAI(
                    model=self.model,
                    google_api_key=self.api_key,
                    temperature=0.2,
                )
                self.enabled = True
                logger.info("Configured ChatGoogleGenerativeAI client")
            except Exception as e:
                logger.error(f"Failed to initialize ChatGoogleGenerativeAI: {e}")
                self.enabled = False
        else:
            self.enabled = False

    def complete(self, prompt: str) -> str:
        """
        Returns LLM text response.
        If API key missing or failure occurs → returns stub JSON.
        """
        if self.enabled:
            try:
                response = self.client.invoke(prompt)
                return response.content if hasattr(response, "content") else str(response)

            except Exception as e:
                logger.error(f"Error calling Gemini model: {e}")
                return "Error: Could not generate response."

        # ---------- Stub Mode ----------
        logger.info("LLMClient running in stub mode. Returning sample JSON.")

        sample = {
            "summary_short": [
                "Topic overview and purpose",
                "Key decision made",
                "Assigned action items",
                "Risks and blockers",
                "Next meeting/time"
            ],
            "summary_detailed": "This is a sample detailed summary generated by stub LLM.",
            "discussion_flow": ["Intro by PM", "Requirements discussion", "Task assignment", "Wrap-up"],
            "timeline": [
                {"timestamp": "00:02", "topic": "Introductions"},
                {"timestamp": "00:10", "topic": "Requirements & scope"}
            ],
            "action_items": [
                {"task": "Create project plan", "assigned_to": "Alice", "deadline": "2025-12-10"}
            ],
            "speaker_sentiment": {
                "Alice": "positive",
                "Bob": "neutral"
            }
        }

        return json.dumps(sample)

